### ISSUE TITLE
Awarded category no longer retrievable

### ISSUE THREAD

**Issue by ChosenOne912** [jc9108/expanse#41]
I noticed that my content hadn't updated in a few days. When I looked at the logs for the application, I saw this error happening every time it went to update.

```
StatusCodeError: 404 - {"message":"Not Found","error":404}
    at new StatusCodeError (/app/backend/node_modules/request-promise-core/lib/errors.js:32:15)
    at /app/backend/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/app/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/app/backend/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/app/backend/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/app/backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/backend/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/app/backend/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21) {
  statusCode: 404,
  error: { message: 'Not Found', error: 404 },
  options: {
    gzip: true,
    json: true,
    headers: {
      'user-agent': 'web:expanse:v=1.2.11 (hosted by u/<username>)'
    },
    baseUrl: 'https://oauth.reddit.com',
    qs: { raw_json: 1, count: 9999, limit: 5 },
    auth: {
    },
    resolveWithFullResponse: true,
    timeout: 30000,
    transform: [Function: transform],
    uri: 'u/<username>/gilded/given',
    method: 'GET',
    callback: [Function: RP$callback],
    simple: true,
    transform2xxOnly: false
  },
``` 

The `/gilded/given` uri is what feeds the `awarded` category. It appears that this retrieval is now failing and causing the content to not update. I believe this has something to do with the rework to Reddit Gold that they announced a few days before I first saw this issue.

https://support.reddithelp.com/hc/en-us/articles/360043034412-What-is-a-Reddit-premium-membership-

It seems like this app may need to remove the `awarded` category.

**Comment by DnanaDev** [comment]
Facing the same error, were you able to fix this? do we need @jc9108 to help out?

I have resorted to import data from Reddit Data Exports for the time being,

**Comment by sugoidogo** [comment]
https://github.com/jc9108/expanse/blob/bc118aebebf0fb2f1481147bbe443fd03bb7f58e/backend/model/user.mjs#L108
https://www.reddit.com/dev/api/#GET_user_{username}_{where}
There's no more mention of "awarded" in the api docs, just the one gilded endpoint. I'm not super familiar with the reddit api, but maybe updating the url in expanse would be enough?
