### ISSUE TITLE
Expanse isnt being updated

### ISSUE THREAD

**Issue by Wildzin** [jc9108/expanse#43]
After importing my reddit csv files, docker has been running for the past week without updating expanse. I've tried restarting the docker container and it continues to import. There is maybe 50,000 links from all the cvs imported.

**Comment by jc9108** [comment]
what version are you on and can you provide error logs?

**Comment by Wildzin** [comment]
idk how to check the version but the docker logs for expanse-app-1 are 
importing (500) (saved) items
importing (7) (hidden) items
importing (500) (created) items
importing (500) (upvoted) items
importing (500) (downvoted) items
ratelimit reached
StatusCodeError: 404 - {"message":"Not Found","error":404}
    at new StatusCodeError (/app/backend/node_modules/request-promise-core/lib/errors.js:32:15)
    at /app/backend/node_modules/request-promise-core/lib/plumbing.js:97:41
    at tryCatcher (/app/backend/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/backend/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/app/backend/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromiseCtx (/app/backend/node_modules/bluebird/js/release/promise.js:641:10)
    at _drainQueueStep (/app/backend/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/app/backend/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/app/backend/node_modules/bluebird/js/release/async.js:102:5)
    at Async.drainQueues [as _onImmediate] (/app/backend/node_modules/bluebird/js/release/async.js:15:14)
    at process.processImmediate (node:internal/timers:476:21) {
  statusCode: 404,
  error: { message: 'Not Found', error: 404 `},`

**Comment by jc9108** [comment]
you can find the version on line 30 of your local `expanse/compose.prod.yaml`. if you are not on latest (1.2.12) please update and try again

**Comment by Wildzin** [comment]
The problem had to do with importing the csv file for upvotes and downvotes. Skipping the import of it expanse worked fine
