### ISSUE TITLE
Error in backend

### ISSUE THREAD

**Issue by subzero355** [jc9108/expanse#6]
Getting error while opening `localhost:1301`
```
expanse_frontend_1 exited with code 0
backend_1   |
backend_1   | > prod
backend_1   | > node ./controller/server.mjs
backend_1   |
backend_1   | update all completed
backend_1   | server (expanse) started on (localhost:1301)
backend_1   | [Error: ENOENT: no such file or directory, stat '/backend/build/index.html'] {
backend_1   |   errno: -2,
backend_1   |   code: 'ENOENT',
backend_1   |   syscall: 'stat',
backend_1   |   path: '/backend/build/index.html',
backend_1   |   expose: false,
backend_1   |   statusCode: 404,
backend_1   |   status: 404
backend_1   | }
backend_1   | TypeError: Cannot read properties of undefined (reading 'user')
backend_1   |     at file:///backend/controller/server.mjs:74:42
backend_1   |     at Layer.handle_error (/backend/node_modules/express/lib/router/layer.js:71:5)
backend_1   |     at trim_prefix (/backend/node_modules/express/lib/router/index.js:326:13)
backend_1   |     at /backend/node_modules/express/lib/router/index.js:286:9
backend_1   |     at Function.process_params (/backend/node_modules/express/lib/router/index.js:346:12)
backend_1   |     at next (/backend/node_modules/express/lib/router/index.js:280:10)
backend_1   |     at /backend/node_modules/express/lib/response.js:455:7
backend_1   |     at SendStream.onerror (/backend/node_modules/express/lib/response.js:1071:5)
backend_1   |     at SendStream.emit (node:events:513:28)
backend_1   |     at SendStream.error (/backend/node_modules/send/index.js:270:17)
backend_1   |     at SendStream.onStatError (/backend/node_modules/send/index.js:417:12)
backend_1   |     at onstat (/backend/node_modules/send/index.js:722:26)
backend_1   |     at FSReqCallback.oncomplete (node:fs:206:21)

```

**Comment by subzero355** [comment]
My bad, I was trying to use bind mount and it screwed up, reverting back to volumes works, need to figure out why bind mount doesnt work.
I have this deployed on RPI and trying to access via <local IP>:1301, what should be given in the redirect URL on Reddit app.

**Comment by jc9108** [comment]
you shouldnt edit the compose file really, thats how ive configured it to work

why are you trying to use bind mount?

**Comment by subzero355** [comment]
I want all the data related in the same folder as docker-compose as I have setup backups using Duplicati and it's easy to backup and restore them. It's working now with volumes but need to check the mount part. Also, I run this behind  reverse proxy, so what should be callback url, I get `"invalid redirect_uri parameter"` error if I specify `https://sub.domain.com/callback`

**Comment by subzero355** [comment]
I missed to change the callback URL in .env_prod
